In [1]:
#type in shift+enter to run the code inside the cell
import numpy as np

In [2]:
#casting list into 1d numpy array
vector = np.array([1,2,3])

In [3]:
vector

array([1, 2, 3])

In [4]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(matrix)

numpy.ndarray

In [7]:
#transpose
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
#type in shift+tab to see the api documentation 
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#np.arange(start,stop,stepsize)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
#np.zeros((no_of_rows,no_of_columns))
#pass in tuple of dimension as an argumnet
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
np.ones(7)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
#np.linspace(start,stop,no_of_points)
#returns linearly spaced points between start and stop
#diff between any 2 consecutive points is (stop-start)/(no_of_points-1)
np.linspace(0,5,5)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [14]:
np.logspace(0,10,11)

array([  1.00000000e+00,   1.00000000e+01,   1.00000000e+02,
         1.00000000e+03,   1.00000000e+04,   1.00000000e+05,
         1.00000000e+06,   1.00000000e+07,   1.00000000e+08,
         1.00000000e+09,   1.00000000e+10])

In [15]:
#4*4 identity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
#generate uniform distributed random numbers between 0-1
np.random.rand(5)

array([ 0.57925559,  0.33841919,  0.04747182,  0.67812677,  0.94816233])

In [17]:
#np.random.rand(shape_or_dimension)
np.random.rand(3,3)

array([[ 0.88751012,  0.25616934,  0.54196205],
       [ 0.35773753,  0.87877001,  0.60560997],
       [ 0.5668264 ,  0.79624095,  0.21280654]])

In [18]:
np.random.rand(3,2,3)

array([[[ 0.59364625,  0.99233182,  0.48705498],
        [ 0.60315445,  0.115328  ,  0.01362975]],

       [[ 0.4842023 ,  0.07671774,  0.85231518],
        [ 0.76297216,  0.79435109,  0.66057598]],

       [[ 0.01869845,  0.71821596,  0.93143128],
        [ 0.21056487,  0.38833078,  0.60694521]]])

In [19]:
#generate random number with normal distribution
x = np.random.randn(7)
x

array([ 0.18812727,  0.20823504,  0.7857695 ,  1.00945661,  0.47783596,
        1.62648063,  0.07482254])

In [20]:
print("Mean={mean}, Variance={var}".format(mean=x.mean(),var=x.var()))

Mean=0.6243896504763489, Variance=0.2665025516721015


In [21]:
#generate 10 random integers between 0 to 100
arr = np.random.randint(0,100,10)
arr

array([36, 23, 63, 14, 63, 73, 95, 88, 66, 28])

In [22]:
arr.max()

95

In [23]:
#returns index location of max value
arr.argmax()

6

In [24]:
arr_1d = np.arange(30)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
arr_1d.shape

(30,)

In [26]:
#changing the dimension of an array
arr_2d = arr_1d.reshape(10,3)
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [27]:
arr_2d.shape

(10, 3)

In [28]:
arr_3d = arr_1d.reshape(5,3,2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [29]:
arr_3d.shape

(5, 3, 2)

In [30]:
#return type of data stored in array
arr_3d.dtype

dtype('int64')

In [31]:
arr = np.random.randint(0,100,10)
arr

array([37, 42, 64, 47, 62, 23, 82, 52, 58, 70])

In [32]:
#slicing and indexing in numpy array are same as python list.
arr[2:5]

array([64, 47, 62])

In [33]:
arr[7:]

array([52, 58, 70])

In [34]:
arr[-3:]

array([52, 58, 70])

In [35]:
arr[:7]

array([37, 42, 64, 47, 62, 23, 82])

In [36]:
slice_of_arr = arr[0:3]
slice_of_arr[:] = 100
#changing the slice_of_array will change the original array as well bcoz in numpy slice_of_array is just a view of reference of original array.

In [37]:
arr

array([100, 100, 100,  47,  62,  23,  82,  52,  58,  70])

In [38]:
#use copy method to get the copy of array slice
arr_slice_copy = arr[2:7].copy()
arr_slice_copy

array([100,  47,  62,  23,  82])

In [39]:
arr_slice_copy[:]=0

In [40]:
arr_slice_copy

array([0, 0, 0, 0, 0])

In [41]:
#original arr remains unchanged
arr

array([100, 100, 100,  47,  62,  23,  82,  52,  58,  70])

In [42]:
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [43]:
arr_2d[7]

array([21, 22, 23])

In [44]:
#double bracket notation
arr_2d[7][1]

22

In [45]:
#single bracket comma notation
arr_2d[7,1]

22

In [46]:
arr_2d[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
#grab subarray using slice notation
arr_2d[:3,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [49]:
bool_arr_1d = arr_1d>20
bool_arr_1d

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True], dtype=bool)

In [50]:
#use boolean array for conditional selection (returns only those elements from arr_1d where bool value is true)
arr_1d[bool_arr_1d]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
arr_1d[arr_1d>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
arr_1d


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
#numpy array operations
# adding scalar to all elements of numpy array
arr_1d+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
arr_1d-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [55]:
#elementwise product
arr_1d*7

array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
        91,  98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175,
       182, 189, 196, 203])

In [56]:
arr_1d + arr_1d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [57]:
arr_1d - arr_1d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [58]:
#element wise square root in numpy array
np.sqrt(arr_1d)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481])

In [59]:
np.sin(arr_1d)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388])

In [60]:
np.log(arr_1d)

/Users/ahsan.kamal/datascience/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509,  2.39789527,  2.48490665,  2.56494936,  2.63905733,
        2.7080502 ,  2.77258872,  2.83321334,  2.89037176,  2.94443898,
        2.99573227,  3.04452244,  3.09104245,  3.13549422,  3.17805383,
        3.21887582,  3.25809654,  3.29583687,  3.33220451,  3.36729583])

In [61]:
#element wise exponential
np.exp(arr_1d)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
         3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
         6.56599691e+07,   1.78482301e+08,   4.85165195e+08,
         1.31881573e+09,   3.58491285e+09,   9.74480345e+09,
         2.64891221e+10,   7.20048993e+10,   1.95729609e+11,
         5.32048241e+11,   1.44625706e+12,   3.93133430e+12])

In [62]:
np.max(arr_1d)

29

In [63]:
#standard deviation
np.std(arr_1d)

8.6554414483991895

In [64]:
np.sum(arr_1d)

435

In [65]:
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [66]:
#sum of each rows
arr_2d.sum(axis=1)

array([ 3, 12, 21, 30, 39, 48, 57, 66, 75, 84])

In [67]:
#matrix product
#dot product of 2 arrays (a.b = |a||b|cosQ)
a = np.arange(0,3)
b = np.arange(4,7)
np.dot(a,b)
# a.dot(b)
# b.dot(a)
# np.sum(a*b)
#(a*b).sum()

17

In [68]:
#magnitude_of_a
#np.sqrt((a*a).sum())
np.linalg.norm(a)

2.2360679774997898

In [69]:
cosQ = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosQ

0.86640022544396333

In [70]:
angle = np.arccos(cosQ)
angle

0.5228486448998364

In [71]:
#numpy dot product method is much faster than computing dot product by looping.
from datetime import datetime

a = np.random.rand(100)
b = np.random.rand(100)
no = 100000

def slow_dot_product(a,b):
    result = 0
    for x,y in zip(a,b):
        result+=x*y
    return result  

def fast_dot_product(a,b):
    return np.dot(a,b)

t1 = datetime.now()
for i in range(no):
    slow_dot_product(a,b)
t1 = datetime.now() - t1  

t2 = datetime.now()
for i in range(no):
    fast_dot_product(a,b)
t2 = datetime.now() - t2 
print("numpy dot product is {} times faster.".format(t1.total_seconds()/t2.total_seconds()))

numpy dot product is 28.291678347090276 times faster.


In [72]:
matrix = np.array([[1,2],[3,4]])
#matrix inverse 
matrix_inverse = np.linalg.inv(matrix)
matrix_inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [73]:
#matrix_inverse*matrix is identity matrix
matrix_inverse.dot(matrix)
#matrix.dot(matrix_inverse)

array([[  1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [74]:
#determinant of matrix
np.linalg.det(matrix)

-2.0000000000000004

In [75]:
#pass in 2-d array to extract the diagonal elements
np.diag(matrix)

array([1, 4])

In [76]:
#pass in 1-d array to construct a diagonal array
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [77]:
#sum of diagonal elements
np.trace(matrix)

5

In [78]:
#outer product c = a * b.T
a = np.array([1,2])
b = np.array([3,4])
#array([[1],   *  array([[3, 4]])
#       [2]])
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [79]:
#inner product is same as a.dot(b)
np.inner(a,b)

11

In [80]:
#Covariance indicates the level to which two variables vary together.
data_matrix = np.random.randn(4,3)
cov_matrix = np.cov(data_matrix.T)
cov_matrix

array([[ 0.04277999,  0.0422632 , -0.09360547],
       [ 0.0422632 ,  0.51028599, -0.60004628],
       [-0.09360547, -0.60004628,  0.75520737]])

In [81]:
#to get tuple of eigen values and eigen vector
#matrix*eigen_vector = eigen_value*eigen_vector
np.linalg.eigh(cov_matrix)

(array([  1.54584609e-04,   5.48181478e-02,   1.25330062e+00]),
 array([[-0.60557115,  0.7915819 ,  0.08174151],
        [-0.58474476, -0.51228991,  0.62899334],
        [-0.53977509, -0.33310229, -0.77310136]]))

In [82]:
#solving linear matrix equation
# A*x = y or x=inv(A)*y
A = np.array([[1,2],[3,4]])
y = np.array([5,6])
x = np.linalg.inv(A).dot(y)
x

array([-4. ,  4.5])

In [83]:
#A.dot(x)=y
A.dot(x)

array([ 5.,  6.])

In [84]:
#easy way to solve linear matrix equation in numpy is
np.linalg.solve(A,y)

array([-4. ,  4.5])

Ref: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html